# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.includeDefaultModules = false;
  boot.loader.systemd-boot.editor = false;
  programs.command-not-found.enable = false;
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  powerManagement.cpuFreqGovernor = "powersave";
  zramSwap.enable = true;
  zramSwap.memoryPercent = 20; # ~3.2 GB on 16 GB RAM
  services.auto-epp.enable = true;

  # Switch to chrony since it's preferred for laptops
  services.chrony.enable = true;
  persist.location.caches.contents = [ "/var/lib/chrony/" ];
  services.timesyncd.enable = false;

  services.power-profiles-daemon.enable = true;
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = true;
}
